### ISSUE TITLE
NTP server does not remember the state of WiFi

### ISSUE THREAD

**Issue by rudiyalex** [Montecri/GNSSTimeServer#18]
NTP server is connected via ethernet and wifi. I turn off wifi by long pressing the button so that the server works only via ethernet. After rebooting the server, wifi turns on again, and does not remember the last state that it was turned off by the button

**Comment by Montecri** [comment]
Good feedback. Will save that in the preferences so it sticks across reboots.

Thanks!

**Comment by Montecri** [comment]
Just updated the code. Now it is saving WiFi status to LittleFS and restoring last status on boot.

Please test and let me know.

Thanks & Regards,

- Cristiano
